### ISSUE TITLE
Make it responsive 

### ISSUE THREAD

**Issue by SallamAltanna** [IsraaMoqbel/memehub#3]
:stuck_out_tongue_winking_eye:

**Comment by IsraaMoqbel** [comment]
I'll be very thankful if you contribute in this!
I'll give you a very beautiful origami :heart_eyes:

**Comment by SallamAltanna** [comment]
> I'll be very thankful if you contribute in this!
> I'll give you a very beautiful origami

You must be kidding 😂😂😂
No thanks I hate origami 😛

**Comment by IsraaMoqbel** [comment]
:cry: :cry: :cry:
don't say that you hate origami! it makes me sad!
